version: '3'

services:
  mongodb:
    image: mongo:4.0.10
    container_name: "todo-mongodb"
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/mongologs
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
